AWSTemplateFormatVersion: 2010-09-09
Description: |
  first template to create ec2 intstance 
Resources:
  testcftec2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-09298640a92b2d12c
      InstanceType: t2.micro
      KeyName: !Ref ec2keypair
      SecurityGroups: 
        - Ref: SSHSecurityGroup

  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Allow http to client host"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ec2keypair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: cfttest123





