- 
  name: "starting apache server on target"
  hosts: sqlserver0
  tasks:
    -
      name: "starting...."
      ansible.builtin.service: 
         name: apache2
         state: stopped  #started
      become: true
      
# Here for changing the state of apache2 you require SUDO previleges
# so you have to use "become: true" in the file to get it  
# USE BELOW CAMMAND WHILE EXECTUING THIS FILE 
# ansible-playbook module/service/service1.yml -i inventory.txt -u afzal --ask-pass -K

