name: Upload Changed Files to Azure Blob Storage

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Intro-S3/**'

jobs:
  sync-to-azure:
    runs-on: ubuntu-latest
    environment:
      name: 'SECRET'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure using service principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set environment variable for SAS token
        run: echo "SAS_TOKEN=${{ secrets.SECRET }}" >> $GITHUB_ENV

      - name: Upload files to Azure Blob Storage
        run: |
          az storage blob upload-batch \
            --account-name stractfortempandscript \
            --destination script \
            --source Intro-S3 \
            --overwrite \
            --sas-token "$SAS_TOKEN"
